apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: io
    labels:
      istio-injection: enabled
- apiVersion: v1
  kind: Namespace
  metadata:
    name: mylb
    annotations:
      meta.helm.sh/release-name: micro
      meta.helm.sh/release-namespace: mylb
    labels:
      istio-injection: enabled
      app.kubernetes.io/managed-by: Helm