apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: io
    labels:
      istio-injection: enabled
- apiVersion: v1
  kind: Namespace
  metadata:
    name: mylb
    labels:
      istio-injection: enabled
      app.kubernetes.io/managed-by: Helm
      kubernetes.io/metadata.name: mylb