templates:
  nameOverride: config-server
  fullnameOverride: config-server
  kind: Deployment
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/rlm/config-server
    pullPolicy: Always
    tag: 0.0.1
  env:
    SERVER_PORT: 80
    MANAGEMENT_SERVER_PORT: 9000
    SECURITY_USER_NAME: default
    SECURITY_USER_PASSWORD: M1h62Gj3Uy54r
    RABBITMQ_VIRTUAL_HOST: /dev
    RABBITMQ_HOST: rabbitmq
    RABBITMQ_PORT: 5672
    RABBITMQ_USERNAME: dev
    RABBITMQ_PASSWORD: KK_fyw4bnmdf4Ksp7IMYuPWD@20stdt^tn50jlsfy
    HOSTNAME: "${POD_NAME}.config-server.${POD_NAMESPACE}.svc.cluster.local"
  environment:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.uid
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  service:
    clusterIP: None
    spec:
    - port: 80
      protocol: TCP
      name: http
    - port: 9000
      protocol: TCP
      name: tcp-actuator
  livenessProbe:
    initialDelaySeconds: 25
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
    timeoutSeconds: 5
    httpGet:
      path: /actuator/health/liveness
      port: tcp-actuator
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 10
    httpGet:
      path: /actuator/health/readiness
      port: tcp-actuator