spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  config:
    import:
    - classpath:yaml/actuator.yaml
    - classpath:yaml/encrypt.yaml
    - classpath:yaml/logging.yaml
    - classpath:yaml/security.yaml
    - classpath:yaml/server.yaml
    - classpath:git.yaml
    - classpath:rabbitmq.yaml