server:
  servlet:
    session:
      cookie:
        name: MICRO-SERVER
eureka:
  client:
    jerseyEnabled: false
    restclientEnabled: false
    webclientEnabled: true
aj:
  captcha:
    cacheType: redis
    jigsaw: classpath:images/jigsaw
    picClick: classpath:images/pic-click
    type: default
    waterMark: localhost
    slipOffset: 5
    aesStatus: true
    interferenceOptions: 0
spring:
  thymeleaf:
    cache: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  sql:
    init:
      mode: ${DB_INIT_MODE:ALWAYS}
      schemaLocations:
      - classpath:database/schema.sql
      - classpath:org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql
      - classpath:org/springframework/security/oauth2/server/authorization/oauth2-authorization-consent-schema.sql
      - classpath:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql
      continueOnError: false
      separator: ;