spring:
  cloud:
    loadbalancer:
      configurations: hints
      hintHeaderName: x-lb-hint
      hint:
        default: ${HINT:mylb}
eureka:
  auth:
    secretKey: ${EUREKA_AUTH_SECRETKEY:123654}
  instance:
    hostname: ${POD_SERVICE_NAME}.${POD_NAMESPACE}
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${eureka.instance.nonSecurePort}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    metadataMap:
      hint: ${HINT:mylb}
      POD_IP: ${POD_IP}
      POD_SERVICE_NAME: ${POD_SERVICE_NAME}
      POD_NAMESPACE: ${POD_NAMESPACE}
  client:
    jersey.enabled: ${eureka.client.jerseyEnabled:false}
    restclient.enabled: ${eureka.client.restclientEnabled:true}
    webclient.enabled: ${eureka.client.webclientEnabled:false}
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${FETCH_REGISTRY:true}
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}