eureka:
  auth.secretKey: ${EUREKA_AUTH_SECRETKEY:123654}
  datacenter: micro
  environment: ${spring.profiles.active}
  instance:
    hostname: ${HOSTNAME}
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${eureka.instance.nonSecurePort}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  server:
    enableSelfPreservation: true
    peerNodeReadTimeoutMs: 5000
    evictionIntervalTimerInMs: 20000
    responseCacheUpdateIntervalMs: 10000
    useReadOnlyResponseCache: true
  client:
    jersey.enabled: false
    restclient.enabled: false
    webclient.enabled: true
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${FETCH_REGISTRY:false}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}