spring:
  cloud:
    loadbalancer:
      configurations: hints
      hintHeaderName: x-lb-hint
      hint:
        default: ${HINT:mylb}
eureka:
  auth.secretKey: ${EUREKA_AUTH_SECRETKEY:123654}
  instance:
    hostname: ${HOSTNAME}
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${eureka.instance.nonSecurePort}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadataMap:
      hint: ${spring.cloud.loadbalancer.hint.default}
      POD_NAMESPACE: ${POD_NAMESPACE}
      POD_SERVICE_NAME: ${POD_SERVICE_NAME}
      POD_NAME: ${POD_NAME}
      POD_IP: ${POD_IP}
  client:
    jersey.enabled: false
    restclient.enabled: false
    webclient.enabled: true
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${FETCH_REGISTRY:true}
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}