spring:
  cloud:
    loadbalancer:
      configurations: hints
      hintHeaderName: x-lb-hint
      hint:
        default: ${HINT:mylb}
eureka:
  auth.secretKey: ${EUREKA_AUTH_SECRETKEY:123654}
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ip-address}
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${eureka.instance.nonSecurePort}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    metadataMap:
      hint: ${HINT:mylb}
  client:
    jersey.enabled: ${eureka.client.jerseyEnabled:false}
    restclient.enabled: ${eureka.client.restclientEnabled:true}
    webclient.enabled: ${eureka.client.webclientEnabled:false}
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${FETCH_REGISTRY:true}
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}