spring:
  data:
    redis:
      database: 2
      host: redis
      port: 6379
      password: UPsfyIREQt^Md0jlYuPWtREf4Ksp7Ibn5tKK
      timeout: 10s
      lettuce:
        pool:
          maxActive: 256
          maxWait: 2000ms
          maxIdle: 10
          minIdle: 5