{{- $fullName := include "postgres.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: tcp
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
