fullnameOverride: redis
image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: 7.4.1
env:
  TZ: Asia/Shanghai
  REQUIREPASS: PASSWORD
service:
  type: ClusterIP
  port: 6379
readinessProbe:
  exec:
    command:
    - redis-cli
    - ping
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  exec:
    command:
    - redis-cli
    - ping
  initialDelaySeconds: 15
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 6
  timeoutSeconds: 5