global:
  env:
    TZ: Asia/Shanghai
    REQUIREPASS: KK_fyw4bnmdf4Ksp7IMYuPWD@20stdt^tn50jlsfy
templates:
  version: 7.4.1
  nameOverride: redis
  fullnameOverride: redis
  autoBindCommonEnv: false
  kind: StatefulSet
  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: 7.4.1
  service:
    clusterIP: None
    spec:
    - port: 6379
      protocol: TCP
      name: tcp-redis
  volumes:
  - name: redis-lib
    hostPath:
      path: /var/lib/redis
  - name: redis-conf
    configMap:
      name: redis-configmap
      items:
      - key: redis.conf
        path: redis.conf
  volumeMounts:
  - name: redis-lib
    mountPath: /var/lib/redis
  - name: redis-conf
    mountPath: /etc/redis/redis.conf