server:
  port: ${SERVER_PORT:8002}
  shutdown: graceful
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8092}
spring:
  application:
    name: CORE-WEB
  profiles:
    active: ${PROFILES_ACTIVE:test}
  config:
    import: configserver:https://gw.renlm.cn/config
  cloud:
    config:
      username: ${SECURITY_USER_NAME:default}
      password: ${SECURITY_USER_PASSWORD:123654}
      name: eureka-client,logging,actuator,otel,core-web,postgres,redis,key-store
      profile: ${spring.profiles.active}
      label: master
      failFast: true