server:
  port: ${SERVER_PORT:8002}
  shutdown: graceful
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8092}
spring:
  application:
    name: CORE-WEB
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  config:
    import: configserver:${CONFIGSERVER:http://localhost:7001/config}
  cloud:
    config:
      username: ${SECURITY_USER_NAME:default}
      password: ${SECURITY_USER_PASSWORD:123654}
      name: eureka-client,logging,actuator,core-web,mysql,redis,key-store
      profile: ${spring.profiles.active}
      label: master
      failFast: true