global:
  http_config: /etc/prometheus/http_config.yaml
scrape_configs:
- job_name: otel-collector
  scrape_interval: 10s
  static_configs:
  - targets: [otel-collector:8888]
  - targets: [otel-collector:9999]
