# https://prometheus.io/docs/prometheus/latest/getting_started/
# apt install -y apache2-utils
# htpasswd -b -nBC12 default M1h62Gj3Uy54r
basic_auth_users:
  default: $2y$12$wTt0jufTLAzjSnIW.ZFQ4.QFkxeqo1pclz8GiSLbAEoQkwRUkUMFq