global:
  env:
    TZ: Asia/Shanghai
    RABBITMQ_DEFAULT_VHOST: /dev
    RABBITMQ_DEFAULT_USER: dev
    RABBITMQ_DEFAULT_PASS: KK_fyw4bnmdf4Ksp7IMYuPWD@20stdt^tn50jlsfy
templates:
  version: 4.0.5
  nameOverride: rabbitmq
  fullnameOverride: rabbitmq
  autoBindCommonEnv: false
  kind: StatefulSet
  image:
    repository: rabbitmq
    pullPolicy: IfNotPresent
    tag: 4.0.5-management
  service:
    clusterIP: None
    spec:
    - port: 5672
      protocol: TCP
      name: tcp-amqp
    - port: 15672
      protocol: TCP
      name: http
  volumes:
  - name: rabbitmq-lib
    hostPath:
      path: /var/lib/rabbitmq
  volumeMounts:
  - name: rabbitmq-lib
    mountPath: /var/lib/rabbitmq