fullnameOverride: rabbitmq
image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: 4.0.4-management
env:
  TZ: Asia/Shanghai
  RABBITMQ_DEFAULT_VHOST: /micro
  RABBITMQ_DEFAULT_USER: micro
  RABBITMQ_DEFAULT_PASS: PASSWORD
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "15692"
service:
  type: ClusterIP
  port: 15672
  amqpPort: 5672
readinessProbe:
  initialDelaySeconds: 25
  periodSeconds: 5
  httpGet:
    path: /
    port: 15672
    scheme: HTTP