global:
  env:
    TZ: Asia/Shanghai
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: KK_fyw4bnmdf4Ksp7IMYuPWD@20stdt^tn50jlsfy
templates:
  nameOverride: postgres
  fullnameOverride: postgres
  kind: StatefulSet
  image:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: latest
  env:
    TZ: Asia/Shanghai
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: KK_fyw4bnmdf4Ksp7IMYuPWD@20stdt^tn50jlsfy
  service:
    type: ClusterIP
    spec:
    - port: 5432
      protocol: TCP
      name: tcp-postgres
  volumes:
  - name: postgres-data
    hostPath:
      path: /var/lib/postgresql/data
  - name: postgres-init
    configMap:
      name: postgres-configmap
      items:
      - key: pgpass
        path: .pgpass
      - key: init-user-db.sh
        path: init-user-db.sh
  volumeMounts:
  - name: postgres-data
    mountPath: /var/lib/postgresql/data
  - name: postgres-init
    mountPath: /docker-entrypoint-initdb.d