management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9001}
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        basePath: /actuator
        include: shutdown,health,info,prometheus,monitor