spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/renlm/ConfigRepo.git
          forcePull: true
          cloneOnStart: true
          defaultLabel: master
          search-paths: config/{profile}
          username: ${GIT_USERNAME:renlm}
          password: ${GIT_USERNAME:123654}