# https://opentelemetry.io/zh/docs/collector/configuration/#receivers
# https://opentelemetry.io/zh/docs/collector/internal-telemetry/
# https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/basicauthextension/README.md
# https://clickhouse.com/docs/en/observability/integrating-opentelemetry
extensions:
  basicauth/server:
    htpasswd: 
      inline: |
        default:$2y$12$wTt0jufTLAzjSnIW.ZFQ4.QFkxeqo1pclz8GiSLbAEoQkwRUkUMFq
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318
        auth:
          authenticator: basicauth/server
processors:
  batch: {}
exporters:
  prometheus:
    endpoint: otel-collector:9999
    namespace: monitor
  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s
    database: default
    username: default
    password: KK_fyw4bnmdf4Ksp7IMYuPWD@20stdt^tn50jlsfy
    async_insert: true
    ttl: 72h
    compress: lz4
    create_schema: true
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
service:
  extensions: [basicauth/server]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
  telemetry:
    metrics:
      readers:
      - pull:
          exporter:
            prometheus:
              host: otel-collector
              port: 8888
