receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318
processors:
  batch:
    timeout: 5s
    send_batch_size: 100000
exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: otel-collector:8889
    namespace: monitor
  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s
    database: logging
    username: logging
    password: KK_fyw4bnmdf4Ksp7IMYuPWD@20stdt^tn50jlsfy
    async_insert: true
    ttl: 72h
    compress: lz4
    create_schema: true
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    timeout: 5s
    metrics_tables:
      gauge: 
        name: "otel_metrics_gauge"
      sum: 
        name: "otel_metrics_sum"
      summary: 
        name: "otel_metrics_summary"
      histogram: 
        name: "otel_metrics_histogram"
      exponential_histogram: 
        name: "otel_metrics_exp_histogram"
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
extensions:
  health_check: {}
  pprof:
    endpoint: otel-collector:1888
  zpages:
    endpoint: otel-collector:55679
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, clickhouse]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, clickhouse]