apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-configmap
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data:
  init-db.sh: |-
    #!/bin/bash
    set -e
    
    # https://clickhouse.com/docs/en/engines/table-engines
    clickhouse client --user {{ .Values.templates.env.CLICKHOUSE_USER }} -n <<-EOSQL
        CREATE DATABASE dev;
        CREATE USER dev IDENTIFIED BY '{{ .Values.templates.env.CLICKHOUSE_PASSWORD }}';
        GRANT CREATE NAMED COLLECTION ON local_mysql_dev TO dev;
        GRANT CREATE NAMED COLLECTION ON local_postgres_dev TO dev;
        GRANT CREATE NAMED COLLECTION ON local_redis_dev TO dev;
        GRANT ALL ON dev.* TO dev;
        use dev;
        CREATE NAMED COLLECTION local_mysql_dev AS host = 'mysql', port = 3306, database = 'dev', user = 'dev', password = '{{ .Values.templates.env.CLICKHOUSE_PASSWORD }}';
        CREATE NAMED COLLECTION local_postgres_dev AS host = 'postgres', port = 5432, database = 'dev', schema = 'public', user = 'dev', password = '{{ .Values.templates.env.CLICKHOUSE_PASSWORD }}';
        CREATE NAMED COLLECTION local_redis_dev AS host = 'redis', port = 6379, db_index = 0, pool_size = 16, password = '{{ .Values.templates.env.CLICKHOUSE_PASSWORD }}';
    EOSQL

