{{- if not .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "templates.fullname" . }}
  labels:
    {{- include "templates.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- else if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    {{- range .Values.service.spec }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "templates.selectorLabels" . | nindent 4 }}
{{- end }}