apiVersion: v1
kind: Service
metadata:
  name: {{ include "templates.fullname" . }}
  labels:
    {{- include "templates.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.spec }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "templates.selectorLabels" . | nindent 4 }}
