kind: Deployment
replicaCount: 1
autoBindCommonEnv: true
imagePullSecrets: []
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest
serviceAccount:
  create: false
autoscaling:
  enabled: false
service: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}