replicaCount: 1
imagePullSecrets: []
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest
serviceAccount:
  create: false
service:
  type: ClusterIP
  port: 80
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}
livenessProbe: {}
readinessProbe: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}