spring:
  cloud:
    loadbalancer:
      configurations: hints
      hintHeaderName: x-lb-hint
      hint:
        default: ${HINT:mylb}
eureka:
  auth.secretKey: ${EUREKA_AUTH_SECRETKEY:123654}
  instance:
    preferIpAddress: false
    hostname: localhost
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${server.port}
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 9
    metadataMap:
      hint: ${HINT:mylb}
  client:
    jersey.enabled: false
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:7101/registrar/eureka}