eureka:
  auth.secretKey: ${EUREKA_AUTH_SECRETKEY:123654}
  datacenter: default
  environment: ${spring.profiles.active}
  instance:
    preferIpAddress: false
    hostname: localhost
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${server.port}
  client:
    jersey.enabled: false
    restclient.enabled: false
    webclient.enabled: true
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/registrar/eureka