eureka:
  client:
    jerseyEnabled: false
    restclientEnabled: false
    webclientEnabled: true
spring:
  cloud:
    gateway:
      routes:
      - id: config
        uri: lb://config-server
        predicates:
        - Path=/config/**
        filters:
        - RewriteLocationResponseHeader=AS_IN_REQUEST, Location
        - AddRequestHeader=X-Request-Router, Spring-Cloud-Gateway
        - AddResponseHeader=X-Response-Router, Spring-Cloud-Gateway
      - id: registrar
        uri: lb://eureka-server
        predicates:
        - Path=/registrar/**
        filters:
        - RewriteLocationResponseHeader=AS_IN_REQUEST, Location
        - AddRequestHeader=X-Request-Router, Spring-Cloud-Gateway
        - AddResponseHeader=X-Response-Router, Spring-Cloud-Gateway