spring:
  application:
    name: eureka-server
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  config:
    import: configserver:${CONFIGSERVER:https://default:M1h62Gj3Uy54r@config.renlm.cn}
  cloud:
    config:
      name: eureka-server,logging,actuator,security,redis
      profile: ${spring.profiles.active}
      label: master
      failFast: true