{{- $fullName := include "redis.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-configmap
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |-
    requirepass {{ .Values.env.REQUIREPASS }}
    protected-mode no
    port {{ .Values.service.port }}
    databases 16
    dir /var/lib/redis
