apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
data:
  redis.conf: |-
    requirepass {{ .Values.global.env.REQUIREPASS }}
    protected-mode no
    port 6379
    databases 16
    dir /var/lib/redis