apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data:
  redis.conf: |-
    requirepass {{ .Values.global.env.REQUIREPASS }}
    protected-mode no
    port 6379
    databases 16
    dir /var/lib/redis