apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: postgres
spec:
  hosts:
  - postgres.io
  location: MESH_INTERNAL
  ports:
  - number: 5432
    name: tcp-postgres
    protocol: TCP
  resolution: DNS
  endpoints:
  - address: postgres