apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: tracing
    namespace: {{ .Values.namespace }}
    labels:
      app: jaeger
  spec:
    type: ClusterIP
    ports:
      - name: http-query
        port: 16686
        protocol: TCP
        targetPort: 16686
      - name: grpc-query
        port: 16685
        protocol: TCP
        targetPort: 16685
    selector:
      {{- include "jaeger.selectorLabels" . | nindent 6 }}
- apiVersion: v1
  kind: Service
  metadata:
    name: zipkin
    namespace: {{ .Values.namespace }}
    labels:
      name: zipkin
  spec:
    ports:
      - port: 9411
        targetPort: 9411
        name: http-query
    selector:
      {{- include "jaeger.selectorLabels" . | nindent 6 }}
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-collector
    namespace: {{ .Values.namespace }}
    labels:
      app: jaeger
  spec:
    type: ClusterIP
    ports:
    - name: jaeger-collector-http
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: jaeger-collector-grpc
      port: 14250
      targetPort: 14250
      protocol: TCP
    - port: 9411
      targetPort: 9411
      name: http-zipkin
    - port: 4317
      name: grpc-otel
    - port: 4318
      name: http-otel
    selector:
      {{- include "jaeger.selectorLabels" . | nindent 6 }}