global:
  env:
    TZ: Asia/Shanghai
    MYSQL_DATABASE: dev
    MYSQL_USER: dev
    MYSQL_PASSWORD: KK_fyw4bnmdf4Ksp7IMYuPWD@20stdt^tn50jlsfy
    MYSQL_ROOT_PASSWORD: KK_fyw4bnmdf4Ksp7IMYuPWD@20stdt^tn50jlsfy
templates:
  version: 9.1
  nameOverride: mysql
  fullnameOverride: mysql
  autoBindCommonEnv: false
  kind: StatefulSet
  image:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: 9.1
    args:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --skip-log-bin
  service:
    clusterIP: None
    spec:
    - port: 3306
      protocol: TCP
      name: tcp-mysql
  volumes:
  - name: mysql-lib
    hostPath:
      path: /var/lib/mysql
  - name: mysql-init
    configMap:
      name: mysql-configmap
      items:
      - key: init-user-db.sql
        path: init-user-db.sql
  volumeMounts:
  - name: mysql-lib
    mountPath: /var/lib/mysql
  - name: mysql-init
    mountPath: /docker-entrypoint-initdb.d/init-user-db.sql
    subPath: init-user-db.sql