apiVersion: v2
name: mygraph
type: application
version: 1.0.1
appVersion: 1.0.1
icon: https://github-io.renlm.cn/favicon.ico
description: MyGraph 管理后台，集成经典RABC权限管理、在线画图、ER模型设计与在线文档管理，是一个高度集成的后台模板。
keywords:
- RABC权限管理
- 在线画图
- ER模型设计
- 文档管理
dependencies:
- name: templates
  version: 0.0.1
  repository: file://../../templates