templates:
  nameOverride: mygraph
  fullnameOverride: mygraph
  kind: Deployment
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/rlm/mygraph
    pullPolicy: Always
    tag: 1.0.1
  env:
    TZ: Asia/Shanghai
    SERVER_PORT: 80
    MANAGEMENT_SERVER_PORT: 9000
    DB_INIT_MODE: ALWAYS
    SECURITY_USER_NAME: default
    SECURITY_USER_PASSWORD: M1h62Gj3Uy54r
    CONFIGSERVER: http://config-server/config
    PROFILES_ACTIVE: kubernetes
  service:
    type: ClusterIP
    spec:
    - port: 80
      protocol: TCP
      name: http
    - port: 9000
      protocol: TCP
      name: tcp-actuator
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: tcp-actuator
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: tcp-actuator