global:
  releaseName: gateway-server
templates:
  kind: Deployment
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/rlm/gateway-server
    pullPolicy: Always
    tag: 0.0.1
  env:
    SERVER_PORT: 80
    MANAGEMENT_SERVER_PORT: 9000
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "9000"
    instrumentation.opentelemetry.io/inject-java: "observability/otlp-instrumentation"
  service:
    clusterIP: None
    spec:
    - port: 80
      protocol: TCP
      name: http
    - port: 9000
      protocol: TCP
      name: tcp-actuator
  livenessProbe:
    initialDelaySeconds: 25
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 6
    timeoutSeconds: 5
    httpGet:
      path: /actuator/health/liveness
      port: tcp-actuator
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 10
    httpGet:
      path: /actuator/health/readiness
      port: tcp-actuator