namespace: istio-system
nameOverride: jaeger
fullnameOverride: jaeger
templates:
  version: 1.58
  namespace: istio-system
  nameOverride: jaeger
  fullnameOverride: jaeger
  autoBindCommonEnv: false
  kind: StatefulSet
  image:
    repository: jaegertracing/all-in-one
    pullPolicy: IfNotPresent
    tag: 1.58
  env:
    OTEL_SERVICE_NAME: jaeger
    OTEL_TRACES_SAMPLER: always_off
    BADGER_EPHEMERAL: false
    SPAN_STORAGE_TYPE: badger
    BADGER_DIRECTORY_VALUE: /badger/data
    BADGER_DIRECTORY_KEY: /badger/key
    COLLECTOR_ZIPKIN_HOST_PORT: :9411
    MEMORY_MAX_TRACES: 50000
    QUERY_BASE_PATH: /jaeger
    METRICS_STORAGE_TYPE: prometheus
    PROMETHEUS_SERVER_URL: http://prometheus:9090
    PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR: true
    PROMETHEUS_QUERY_NAMESPACE: monitor_spanmetrics
    PROMETHEUS_QUERY_DURATION_UNIT: ms
    PROMETHEUS_QUERY_NORMALIZE_CALLS: true
    PROMETHEUS_QUERY_NORMALIZE_DURATION: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "14269"
  livenessProbe:
    httpGet:
      path: /
      port: 14269
  readinessProbe:
    httpGet:
      path: /
      port: 14269
  volumes:
  - name: data
    emptyDir: {}
  - name: localtime
    hostPath:
      path: /etc/localtime
  volumeMounts:
  - name: data
    mountPath: /badger
  - name: localtime
    mountPath: /etc/localtime
    readOnly: true