templates:
  fullnameOverride: jenkins
  image:
    repository: jenkins/jenkins
    pullPolicy: IfNotPresent
    tag: lts-jdk17
  securityContext:
    runAsUser: 0
  service:
    type: ClusterIP
    port: 8080
  volumes:
  - name: root-m2
    hostPath:
      path: /root/.m2
  - name: docker-bin
    hostPath:
      path: /usr/bin/docker
  - name: docker-daemon
    hostPath:
      path: /etc/docker
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: jenkins-home
    hostPath:
      path: /var/jenkins_home
  - name: localtime
    hostPath:
      path: /etc/localtime
  volumeMounts:
  - name: root-m2
    mountPath: /root/.m2
  - name: docker-bin
    mountPath: /usr/bin/docker
  - name: docker-daemon
    mountPath: /etc/docker/daemon.json
    subPath: daemon.json
  - name: docker-sock
    mountPath: /var/run/docker.sock
  - name: jenkins-home
    mountPath: /var/jenkins_home
  - name: localtime
    mountPath: /etc/localtime
    readOnly: true