templates:
  version: 2.491
  nameOverride: jenkins
  fullnameOverride: jenkins
  autoBindCommonEnv: false
  kind: StatefulSet
  image:
    repository: jenkins/jenkins
    pullPolicy: IfNotPresent
    tag: 2.491
  podSecurityContext:
    runAsUser: 0
  service:
    type: ClusterIP
    spec:
    - port: 8080
      protocol: TCP
      name: http
  volumes:
  - name: root-m2
    hostPath:
      path: /root/.m2
  - name: docker-bin
    hostPath:
      path: /usr/bin/docker
  - name: docker-libexec
    hostPath:
      path: /usr/libexec/docker
  - name: docker-daemon
    hostPath:
      path: /etc/docker
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: jenkins-home
    hostPath:
      path: /var/jenkins_home
  - name: localtime
    hostPath:
      path: /etc/localtime
  volumeMounts:
  - name: root-m2
    mountPath: /root/.m2
  - name: docker-bin
    mountPath: /usr/bin/docker
  - name: docker-libexec
    mountPath: /usr/libexec/docker
  - name: docker-daemon
    mountPath: /etc/docker/daemon.json
    subPath: daemon.json
  - name: docker-sock
    mountPath: /var/run/docker.sock
  - name: jenkins-home
    mountPath: /var/jenkins_home
  - name: localtime
    mountPath: /etc/localtime
    readOnly: true