# https://docs.docker.com/reference/compose-file/
services:
  zoo1:
    image: zookeeper:3.8.4
    restart: always
    hostname: zoo1
    ports:
    - 2081:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_CFG_EXTRA: quorum.auth.enableSasl=true
        quorum.auth.learnerRequireSasl=true
        quorum.auth.serverRequireSasl=true
        quorum.auth.learner.loginContext=QuorumLearner
        quorum.auth.server.loginContext=QuorumServer
        quorum.cnxn.threads.size=6
        sessionRequireClientSASLAuth=true
        authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        authProvider.2=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        authProvider.3=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      JVMFLAGS: -Djava.security.auth.login.config=/conf/jaas.conf
    volumes:
    - /root/ConfigRepo/docker/volumes/zookeeper/jaas.conf:/conf/jaas.conf
  zoo2:
    image: zookeeper:3.8.4
    restart: always
    hostname: zoo2
    ports:
    - 2082:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_CFG_EXTRA: quorum.auth.enableSasl=true
        quorum.auth.learnerRequireSasl=true
        quorum.auth.serverRequireSasl=true
        quorum.auth.learner.loginContext=QuorumLearner
        quorum.auth.server.loginContext=QuorumServer
        quorum.cnxn.threads.size=6
        sessionRequireClientSASLAuth=true
        authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        authProvider.2=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        authProvider.3=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      JVMFLAGS: -Djava.security.auth.login.config=/conf/jaas.conf
    volumes:
    - /root/ConfigRepo/docker/volumes/zookeeper/jaas.conf:/conf/jaas.conf
  zoo3:
    image: zookeeper:3.8.4
    restart: always
    hostname: zoo3
    ports:
    - 2083:2181
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_CFG_EXTRA: quorum.auth.enableSasl=true
        quorum.auth.learnerRequireSasl=true
        quorum.auth.serverRequireSasl=true
        quorum.auth.learner.loginContext=QuorumLearner
        quorum.auth.server.loginContext=QuorumServer
        quorum.cnxn.threads.size=6
        sessionRequireClientSASLAuth=true
        authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        authProvider.2=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        authProvider.3=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      JVMFLAGS: -Djava.security.auth.login.config=/conf/jaas.conf
    volumes:
    - /root/ConfigRepo/docker/volumes/zookeeper/jaas.conf:/conf/jaas.conf
networks:
  default:
    external: true
    name: share