apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-env
data:
  SECURITY_USER_NAME: {{ .Values.SECURITY_USER_NAME }}
  SECURITY_USER_PASSWORD: {{ .Values.SECURITY_USER_PASSWORD }}
  CONFIGSERVER: http://config-server.{{ .Release.Namespace }}.svc.cluster.local/config
  PROFILES_ACTIVE: kubernetes