spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  jpa:
    openInView: false
    showSql: true
    hibernate:
      ddlAuto: none
  sql:
    init:
      mode: ${DB_INIT_MODE:ALWAYS}
      schemaLocations:
      - classpath:database/schema/rbac.sql
      dataLocations:
      - classpath:database/data/rbac.sql
      continueOnError: false
      separator: ;