spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/renlm/MicroServer.git
          forcePull: true
          cloneOnStart: true
          defaultLabel: master
          searchPaths: repo/config/{profile}