apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: eureka-server
spec:
  hosts:
  - amqp.renlm.cn
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - port: 80
    - port: 443
    route:
    - weight: 100
      destination:
        host: eureka-server
        port:
          number: 80