apiVersion: v2
name: local
description: A Helm chart for Kubernetes
type: library
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: mychart
  repository: file://./charts/mychart
  condition: mychart.enabled
- name: nginx
  repository: file://./charts/nginx
  condition: nginx.enabled
- name: jaeger
  repository: file://./charts/jaeger
  condition: jaeger.enabled
- name: redis
  repository: file://./charts/redis
  condition: redis.enabled
- name: postgres
  repository: file://./charts/postgres
  condition: postgres.enabled
- name: clickhouse
  repository: file://./charts/clickhouse
  condition: clickhouse.enabled
- name: mysql
  repository: file://./charts/mysql
  condition: mysql.enabled
- name: rabbitmq
  repository: file://./charts/rabbitmq
  condition: rabbitmq.enabled
- name: jenkins
  repository: file://./charts/jenkins
  condition: jenkins.enabled
- name: config
  repository: file://./charts/config
  condition: config.enabled
- name: eureka
  repository: file://./charts/eureka
  condition: eureka.enabled
- name: gateway
  repository: file://./charts/gateway
  condition: gateway.enabled
- name: coreservice
  repository: file://./charts/coreservice
  condition: coreservice.enabled
- name: coreweb
  repository: file://./charts/coreweb
  condition: coreweb.enabled