apiVersion: v2
name: local
description: A Helm chart for Kubernetes
type: library
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: nginx
  repository: file://./charts/nginx
  condition: nginx.enabled
- name: redis
  repository: file://./charts/redis
  condition: redis.enabled
- name: postgres
  repository: file://./charts/postgres
  condition: postgres.enabled
- name: rabbitmq
  repository: file://./charts/rabbitmq
  condition: rabbitmq.enabled
- name: jenkins
  repository: file://./charts/jenkins
  condition: jenkins.enabled
- name: jaeger
  repository: file://./charts/jaeger
  condition: jaeger.enabled
- name: config-server
  repository: file://./charts/config-server
  condition: config-server.enabled
- name: eureka-server
  repository: file://./charts/eureka-server
  condition: eureka-server.enabled
- name: gateway
  repository: file://./charts/gateway
  condition: gateway.enabled