nginx:
  enabled: false
jenkins:
  enabled: false
jaeger:
  enabled: false
redis:
  enabled: false
mysql:
  enabled: false
postgres:
  enabled: false
rabbitmq:
  enabled: false
config-server:
  enabled: false
eureka-server:
  enabled: false
gateway:
  enabled: false