server:
  port: ${SERVER_PORT:8001}
  shutdown: graceful
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8091}
spring:
  application:
    name: core-service
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  config:
    import: configserver:https://gw.renlm.cn/config
  cloud:
    config:
      username: ${SECURITY_USER_NAME:default}
      password: ${SECURITY_USER_PASSWORD:123654}
      name: eureka-client,logging,actuator
      profile: ${spring.profiles.active}
      label: master
      failFast: true