server:
  port: ${SERVER_PORT:8001}
  shutdown: graceful
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8091}
spring:
  application:
    name: CORE-SERVICE
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  config:
    import: configserver:http://localhost:7001/config
  cloud:
    config:
      username: ${SECURITY_USER_NAME:default}
      password: ${SECURITY_USER_PASSWORD:123654}
      name: eureka-client,logging,actuator,otel,core-service,postgres
      profile: ${spring.profiles.active}
      label: master
      failFast: true