spring:
  application:
    name: CORE-SERVICE
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  config:
    import: configserver:https://${SECURITY_USER_NAME:default}:${SECURITY_USER_PASSWORD:123654}@gw.renlm.cn/config/eureka-client,logging,actuator/${spring.profiles.active}/master?fail-fast=true