# https://docs.docker.com/reference/compose-file/
services:
  mygraph:
    image: registry.cn-hangzhou.aliyuncs.com/rlm/mygraph:1.0.1
    container_name: mygraph
    hostname: mygraph
    restart: always
    init: true
    ports:
    - 7080:7080
    - 7090:7090
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:7090/actuator/health
      interval: 5s
      timeout: 5s
      retries: 36
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: 7080
      MANAGEMENT_SERVER_PORT: 7090
      DB_INIT_MODE: NEVER
      SECURITY_USER_NAME: default
      SECURITY_USER_PASSWORD: M1h62Gj3Uy54r
      CONFIGSERVER: http://config-server:7001
networks:
  default:
    external: true
    name: share