fullnameOverride: nginx
replicaCount: 1
imagePullSecrets: []
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: 1.25.5
env:
  TZ: Asia/Shanghai
podAnnotations:
  instrumentation.opentelemetry.io/inject-nginx: observability/otlp-instrumentation
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: nginx-sa
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
resources: {}
livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 6
  timeoutSeconds: 5
  httpGet:
    path: /
    port: http
readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 5
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
volumes:
- name: nginx-init
  configMap:
    defaultMode: 493
    name: nginx-configmap
    items:
    - key: init.sh
      path: init.sh
volumeMounts:
- name: nginx-init
  mountPath: /docker-entrypoint.d/99-my-init.sh
  subPath: init.sh
nodeSelector: {}
tolerations: []
affinity: {}