global:
  env:
    TZ: Asia/Shanghai
templates:
  version: 1.25.5
  nameOverride: nginx
  fullnameOverride: nginx
  autoBindCommonEnv: false
  kind: Deployment
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: 1.25.5
  podAnnotations:
    instrumentation.opentelemetry.io/inject-nginx: observability/otlp-instrumentation
  service:
    clusterIP: None
    spec:
    - port: 80
      protocol: TCP
      name: http
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
  volumes:
  - name: nginx-init
    configMap:
      defaultMode: 493
      name: nginx-configmap
      items:
      - key: init.sh
        path: init.sh
  volumeMounts:
  - name: nginx-init
    mountPath: /docker-entrypoint.d/99-my-init.sh
    subPath: init.sh