templates:
  nameOverride: config
  fullnameOverride: config
  kind: Deployment
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/rlm/config-server
    pullPolicy: Always
    tag: 0.0.1
  env:
    SERVER_PORT: 7001
    MANAGEMENT_SERVER_PORT: 9001
    SECURITY_USER_NAME: default
    SECURITY_USER_PASSWORD: M1h62Gj3Uy54r
  service:
    type: ClusterIP
    spec:
    - port: 7001
      protocol: TCP
      name: http
    - port: 9001
      protocol: TCP
      name: tcp-actuator
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: tcp-actuator
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: tcp-actuator