# https://opentelemetry.io/zh/docs/collector/configuration/#receivers
# https://github.com/jaegertracing/jaeger/tree/main/docker-compose/monitor
# https://github.com/open-telemetry/opentelemetry-operator/tree/main/cmd/otel-allocator#prometheuscr-specifics
# https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetryiov1beta1
# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector
# https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: observability
spec:
  image: otel/opentelemetry-collector-contrib
  mode: deployment
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
  env:
  - name: TZ
    value: Asia/Shanghai
  config:
    receivers:
      otlp:
        protocols:
          grpc: 
            endpoint: 0.0.0.0:4317
          http: 
            endpoint: 0.0.0.0:4318
    processors:
      batch: {}
      resource:
        attributes:
        - action: insert
          key: loki.resource.labels
          value: >-
            k8s.deployment.name,
            k8s.namespace.name,
            k8s.node.name,
            k8s.pod.name
    exporters:
      debug:
        verbosity: detailed
      prometheus:
        endpoint: 0.0.0.0:9090
        namespace: monitor
      zipkin:
        endpoint: http://zipkin.istio-system.svc:9411/api/v2/spans
        tls:
          insecure: true
      loki:
        endpoint: http://loki.istio-system.svc:3100/loki/api/v1/push
        tls:
          insecure: true
    connectors:
      spanmetrics:
        namespace: spanmetrics
        histogram:
          explicit:
            buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
        dimensions:
          - name: http.method
            default: GET
          - name: http.status_code
        exemplars:
          enabled: true
        exclude_dimensions:
          - status.code
        dimensions_cache_size: 1000
        aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE
        metrics_flush_interval: 15s
        metrics_expiration: 5m
        events:
          enabled: true
          dimensions:
            - name: exception.type
            - name: exception.message
        resource_metrics_key_attributes:
          - service.name
          - telemetry.sdk.language
          - telemetry.sdk.name
    service:
      pipelines:
        metrics:
          receivers: [otlp, spanmetrics]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [spanmetrics, zipkin]
        logs:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [debug, zipkin, loki]
