# https://github.com/open-telemetry/opentelemetry-operator/blob/main/README.md#opentelemetry-auto-instrumentation-injection
# https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#instrumentation
apiVersion: v1
kind: List
items:
- apiVersion: opentelemetry.io/v1alpha1
  kind: Instrumentation
  metadata:
    name: otlp-instrumentation
    namespace: observability
  spec:
    defaults:
      useLabelsForResourceAttributes: true
    exporter:
      endpoint: http://otel-collector.observability.svc:4317
    propagators:
    - tracecontext
    - baggage
    - b3
    sampler:
      type: parentbased_always_on
    env:
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: grpc
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    nginx:
      attrs:
      - name: NginxModuleOtelExporterEndpoint
        value: http://otel-collector.observability.svc:4317
      - name: NginxModuleTraceAsError
        value: OFF
    java:
      image: otel/autoinstrumentation-java:latest
      env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc