apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  init-user-db.sql: |-
    CREATE DATABASE mygraph;
    CREATE USER 'mygraph'@'%' IDENTIFIED WITH caching_sha2_password BY '{{ .Values.global.env.MYSQL_PASSWORD }}';
    GRANT ALL PRIVILEGES ON mygraph.* to 'mygraph'@'%';
    FLUSH PRIVILEGES;
