templates:
  nameOverride: eureka
  fullnameOverride: eureka
  kind: StatefulSet
  replicaCount: 3
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/rlm/eureka-server
    pullPolicy: Always
    tag: 0.0.1
  env:
    SERVER_PORT: 80
    MANAGEMENT_SERVER_PORT: 9001
    SECURITY_USER_NAME: default
    SECURITY_USER_PASSWORD: M1h62Gj3Uy54r
    CONFIGSERVER: http://config/config
    EUREKA_SERVER: http://eureka-0.eureka.{{ .Release.Namespace }}/registrar/eureka,http://eureka-1.eureka.{{ .Release.Namespace }}/registrar/eureka,http://eureka-2.eureka.{{ .Release.Namespace }}/registrar/eureka
    EUREKA_AUTH_SECRETKEY: KK_fyw4bnmdf4Ksp7IMYuPWD@20stdt^tn50jlsfy
    HOSTNAME: ${POD_NAME}.eureka
    PROFILES_ACTIVE: kubernetes
  environment:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  service:
    type: ClusterIP
    spec:
    - port: 80
      protocol: TCP
      name: http
    - port: 9001
      protocol: TCP
      name: tcp-actuator
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: tcp-actuator
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: tcp-actuator